module.exports = {
  rules: {
    'node/callback-return': 'error',
    'node/exports-style': 'off',
    'node/file-extension-in-import': 'off',
    'node/global-require': 'off',
    'node/handle-callback-err': 'error',
    'node/no-callback-literal': 'error',
    'node/no-deprecated-api': ['error', { version: '>=12.0.0' }],
    'node/no-exports-assign': 'off',
    'node/no-extraneous-import': 'off',
    'node/no-extraneous-require': 'off',
    'node/no-missing-import': 'off',
    'node/no-missing-require': 'off',
    'node/no-mixed-requires': 'off',
    'node/no-new-require': 'off',
    'node/no-path-concat': 'error',
    'node/no-process-env': 'off',
    'node/no-process-exit': 'error',
    'node/no-restricted-import': 'off',
    'node/no-restricted-require': 'off',
    'node/no-sync': 'off',
    'node/no-unpublished-bin': 'off',
    'node/no-unpublished-import': 'off',
    'node/no-unpublished-require': 'off',
    'node/no-unsupported-features/es-builtins': ['error', { version: '>=14.0.0' }],
    'node/no-unsupported-features/es-syntax': ['error', { version: '>=14.0.0', ignores: ['modules'] }],
    'node/no-unsupported-features/node-builtins': ['error', { version: '>=14.0.0' }],
    'node/prefer-global/buffer': 'error',
    'node/prefer-global/console': 'off',
    'node/prefer-global/process': 'off',
    'node/prefer-global/text-decoder': 'error',
    'node/prefer-global/text-encoder': 'error',
    'node/prefer-global/url': 'error',
    'node/prefer-global/url-search-params': 'error',
    'node/prefer-promises/dns': 'error',
    'node/prefer-promises/fs': 'error',
    'node/process-exit-as-throw': 'error',
    'node/shebang': 'error'
  }
}
