version: '3.7'

services:
  eslint-configs-nest-demo:
    container_name: eslint-configs-nest-demo
    networks:
      eslint-configs:
        ipv4_address: 172.28.0.3
    build:
      context: .
      dockerfile: dev.Dockerfile
      args:
        - user_id=$UID
        - group_id=$GID
        - user=$USER
    ports:
      - "3001:3001"
    volumes:
      - .:/app
    depends_on:
      - eslint-configs-mongo-dev
    links:
      - eslint-configs-mongo-dev
    environment:
      MONGO_HOST: eslint-configs-mongo-dev
      MONGO_INITDB_DATABASE: eslint-configs-db
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_PORT: 27017
      SERVER_PORT: 3001
      NODE_ENV: development
    working_dir: /app/packages/nest-demo
    command: yarn start-dev

  eslint-configs-react-demo:
    container_name: eslint-configs-react-demo
    networks:
      eslint-configs:
        ipv4_address: 172.28.0.4
    build:
      context: .
      dockerfile: dev.Dockerfile
      args:
        - uid=$UID
        - gid=$GID
        - user=$USER
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    environment:
      TSC_COMPILE_ON_ERROR: "true"
      DISABLE_ESLINT_PLUGIN: "true"
      API_URL: "http://localhost:3001"
    working_dir: /app/packages/react-demo
    command: yarn start

  eslint-configs-mongo-dev:
    container_name: eslint-configs-mongo-dev
    image: mongo:5.0.2
    networks:
      eslint-configs:
        ipv4_address: 172.28.0.5
    environment:
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_ROOT_USERNAME: root

networks:
  eslint-configs:
    name: eslint-configs
    ipam:
      config:
        - subnet: 172.28.0.0/16
