name: Publish to NPM

#on:
#  create:
#    tags:
#      - v*

on:
  push:
    branches:
      - main

env:
  NPM_USER: ${{ secrets.NPM_USER }}
  NPM_PASS: ${{ secrets.NPM_PASS }}
  NPM_EMAIL: ${{ secrets.NPM_EMAIL }}

jobs:
  publish_to_npm:
    runs-on: ubuntu-latest
    steps:
      - name: Use "actions/checkout@master"
        uses: actions/checkout@master
        with:
          fetch-depth: 0

      - name: Checkout HEAD
        run: git checkout ${GITHUB_REF:11}

      - name: Use "actions/setup-node@master"
        uses: actions/setup-node@master
        with:
          node-version: 14

      - name: Setup git config
        run: |
          git config --global user.name ${NPM_USER}
          git config --global user.email ${NPM_EMAIL}

      - name: Login to NPM
        run: npx npm-cli-login

      - name: Publish packages to NPM
        run: npx lerna publish patch --yes
